# -*- coding: utf-8 -*-
"""ComparingModels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohh3TT_vG0XebzAlEgQLyMEiRFIOfDih
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

import math
def mae(target, predicted):
    target, predicted = np.array(target), np.array(predicted)
    return np.mean(np.abs(target - predicted))

def rmse(target, predicted):
  MSE = np.square(np.subtract(target,predicted)).mean() 
  RMSE = math.sqrt(MSE)
  return RMSE

def MAERMSE_lists(text_file):
  file1 = open(text_file, "r")
  a = file1.read()
  lines = a.split(',')
  lines
  MAE_list = []
  RMSE_list = []
  indexes = []
  for x in lines:
    if "RMSE" in x:
      RMSE_list.append(x)
      indexes.append(lines.index(x))
  for i in indexes:
    MAE_list.append(lines[i-1])
    
  MAE_list_sorted = []
  for x in MAE_list:
    colon_index = x.index("MAE:")
    MAE_list_sorted.append(float(x[colon_index + 5:]))
  MAE_list_sorted
  RMSE_list_sorted = []
  for x in RMSE_list:
    colon_index = x.index(":")
    RMSE_list_sorted.append(float(x[colon_index + 2:]))
  return MAE_list_sorted, RMSE_list_sorted

a3,b3 = MAERMSE_lists("output_old_1000500200_2.py")
a40,b40 = MAERMSE_lists("output_new_1000500200_2.py")
a5, b5 = MAERMSE_lists("proper1000500200_RELU.py")
a7, b7 = MAERMSE_lists("proper800300100_ELU.py")
a9, b9 = MAERMSE_lists("proper1000200_ELU.py")
n = min(len(a3), len(a5), len(a7), len(a40), len(a9))

epochs = range(n)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
fig.set_size_inches(15, 10)
plt.title('Comparing the MAE and RMSE of different models')
plt.plot(epochs, a40[:n], color = "royalblue", label = 'Intramolecular hydrogen bonds')
plt.plot(epochs, b40[:n], color = "royalblue", linestyle='dashed')
plt.plot(epochs, a5[:n], color = "skyblue", label = 'Activation function: RELU')
plt.plot(epochs, b5[:n], color = "skyblue", linestyle='dashed')
plt.plot(epochs, a7[:n], color = "mediumaquamarine", label = 'Dense layers: 1000 - 300 - 100')
plt.plot(epochs, b7[:n], color = "mediumaquamarine", linestyle='dashed')
plt.plot(epochs, a9[:n], color = "darkgreen", label = 'Dense layers: 1000 - 200')
plt.plot(epochs, b9[:n], color = "darkgreen", linestyle='dashed')
plt.plot(epochs, a3[:n], color = "firebrick", label = 'Original')
plt.plot(epochs, b3[:n], color = "firebrick", linestyle='dashed')
plt.legend()
plt.xlabel("Epoch")
plt.ylabel("MAE(solid) or RMSE (dotted)")
fig.savefig('comparingmodels.png', bbox_inches = "tight") 
files.download("comparingmodels.png")

plt.show()

mean3 = np.mean(a3[5:30])
mean5 = np.mean(a5[5:30])
mean6 = np.mean(a6[5:30])
mean7 = np.mean(a7[5:30])
mean8 = np.mean(a8[5:30])
mean9 = np.mean(a9[5:30])
print(mean3, mean5, mean6, mean7, mean8,mean9)